model: better_cnn
dataset: cifar10

activation:
  type: custom_relu
  precision: fp32  # Options: fp8, fp16, fp32

training:
  batch_size: 128
  epochs: 50
  learning_rate: 0.01
  optimizer: adam
  print_every_n_epochs: 5

device: cuda

results:
  save_results: true
  results_path: results